/**
 * Created by zhantong on 2016/11/21.
 */
public enum EncodeHintType {
    RS_ERROR_CORRECTION_SIZE,
    RS_ERROR_CORRECTION_LEVEL,
    RAPTORQ_NUMBER_OF_SOURCE_BLOCKS,
    RAPTORQ_REDUNDANT_PERCENT,
    RAPTORQ_REPLACE_LAST_SOURCE_PACKET_AS_REPAIR,
}
